### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by DRT-DISABLED-ACCOUNT** [MoyasiGinko/Leaderboard-Project#4]
# 👋Hey @MoyasiGinko 

Great job with your project, I suggest that you modularize your code, and use the JavaScript entry point to run all of your components.

Breaking the code down into smaller, manageable components that are easier to develop, test, and maintain, makes the code reusable and helps in isolating and fixing issues or making enhancements to specific parts of the codebase without affecting the entire application.

It was a pleasure to work with you again 🚀

**Comment by MoyasiGinko** [comment]
Thank you @wwwdrt for your feedback. I will work on this issue later.

and it was a great pleasure to work with you again too, bro! 🚀
